### PR TITLE
Maven Plugin for Service Proxy

### PR DESCRIPTION
**Pull request by rydnr**
We wanted to run service-proxy in our Maven project, and decided to write this initial plugin.
It works fine for us so far. We run it in isolation from the rest of the plugins.
Please review it and suggest anything you might find inconvenient.

Thank you!

### CODE REVIEW

**Comment by predic8** [comment]
Hi @rydnr,
great contribution. The maven plugin will help me a lot for testing. I am wondering if we should include the plugin into Membrane core or give it a own repository as it is isolated and only depends on Membrane core. We can create the repo or you can do it also on github and we link from the documentation to the repo. It would be great if we can use some lines from your README for that.

**Comment by rrayst** [comment]
The advantage of merging it into the main repo is that we can detect breaking API changes more easily concerning the plugin. (We haven't declared what is public API, and we frequently break some corner during refactoring.)

**Comment by predic8** [comment]
For that we have continuous Integration

Von meinem iPhone gesendet

**Comment by rrayst** [comment]
This effectively has been merged in August of 2016.

**Pull request closed without merging**
